CREATE OR REPLACE FUNCTION OTRS.fncIntToTime(DTDATA INTEGER) RETURN integer
DETERMINISTIC IS SUMHORAS integer; HORACALC integer; MINUTOCALC integer; SEGUNDOCALC integer;
BEGIN
    SUMHORAS := DTDATA;
    HORACALC := FLOOR(SUMHORAS / 3600);
    SUMHORAS := SUMHORAS - (HORACALC * 3600);
    MINUTOCALC := FLOOR(SUMHORAS / 60);
    SUMHORAS := SUMHORAS - (MINUTOCALC * 60);
    SEGUNDOCALC := SUMHORAS;
    RETURN LPAD(HORACALC,2,'0')||':'||LPAD(MINUTOCALC,2,'0')||':'||LPAD(SEGUNDOCALC,2,'0');
END;