CREATE OR REPLACE FUNCTION OTRS.FNCINTEGERTOHOUR(DTDATA INTEGER) RETURN VARCHAR2
DETERMINISTIC IS SUMHORAS integer; HORACALC integer; MINUTOCALC integer; SEGUNDOCALC integer;
BEGIN
    SUMHORAS := DTDATA;
    HORACALC := FLOOR(SUMHORAS / 3600);
    SUMHORAS := SUMHORAS - (HORACALC * 3600);
    MINUTOCALC := FLOOR(SUMHORAS / 60);
    SUMHORAS := SUMHORAS - (MINUTOCALC * 60);
    SEGUNDOCALC := SUMHORAS;
    RETURN HORACALC||':'||MINUTOCALC||':'||SEGUNDOCALC;
END;
