CREATE OR REPLACE FUNCTION OTRS.FNCTOTALHORASUTEIS(ICALENDAR INTEGER, DTINI DATE, DTFIM DATE) RETURN VARCHAR IS
	INITURNO VARCHAR(8);
	FIMTURNO VARCHAR(8);
	RETORNO VARCHAR(10);
    SUMHORAS INTEGER;
    COUNTDIAS INTEGER;
    ICOUNT INTEGER;
    HORAINIACUMULADA INTEGER;
    HORAFIMACUMULADA INTEGER;
    HORACALC INTEGER;
    MINUTOCALC INTEGER;
    SEGUNDOCALC INTEGER;
    DATACALCINI DATE;
    DATACALCFIM DATE;
    DATAPROXIMA DATE;
	ISELECT INTEGER;
BEGIN
	-- CALCULA INICIO E TERMINO DO TURNO DO CALENDARIO
	IF (ICALENDAR = 1) THEN
        -- CENTRAL DE SERVIÇO
		INITURNO := '08:00:00';
		FIMTURNO := '20:00:00';
	ELSIF (ICALENDAR = 2) THEN
			-- ANALISE&SUPORTE
			INITURNO := '09:00:00';
			FIMTURNO := '19:00:00';
	ELSE
        -- SUPORTE24H
		INITURNO := '00:00:00';
		FIMTURNO := '23:59:59';
	END IF;
    
	IF (ABS(DATEDIFF(DTFIM,DTINI)) = 0) THEN
		-- TRATANDO DATAHORA INICIAL
    	IF (FNCTIMETOINT(DTINI) < FNCTIME2TOINT(INITURNO)) THEN
			-- SE O TEMPO É ANTERIOR AO HORARIOTRABALHO ;;;  TIMESTAMPADD(HOUR,SUBSTRING(INITURNO,1,2),DATE(DTINI));
			DATACALCINI := (TO_TIMESTAMP(DTINI,'HH24:MI:SS') + (SUBSTR(INITURNO,1,2)/24));
		ELSE
			IF (FNCTIMETOINT(DTINI) > FNCTIME2TOINT(FIMTURNO)) THEN
				-- SE O TEMPO É POSTERIOR AO HORARIOTRABALHO ;;; TIMESTAMPADD(HOUR,SUBSTRING(INITURNO,1,2),DATE(DTINI));
				DATACALCINI := (TO_TIMESTAMP(DTINI,'HH24:MI:SS') + (SUBSTR(INITURNO,1,2)/24));
			ELSE
				DATACALCINI := DTINI;
			END IF;
		END IF;
		-- TRATANDO DATAHORA FINAL
		IF (FNCTIMETOINT(DTFIM) > FNCTIME2TOINT(FIMTURNO)) THEN
			-- SE O TEMPO É POSTERIOR AO HORARIOTRABALHO ;;; TIMESTAMPADD(HOUR,SUBSTRING(INITURNO,1,2),DATE(DTINI));
			IF (FNCTIMETOINT(DTINI) > FNCTIME2TOINT(FIMTURNO)) THEN
				DATACALCFIM := (TO_TIMESTAMP(DTINI,'HH24:MI:SS') + (SUBSTR(INITURNO,1,2)/24));
			ELSE -- TIMESTAMPADD(HOUR,SUBSTRING(FIMTURNO,1,2),DATE(DTFIM));
				DATACALCFIM := (TO_TIMESTAMP(DTFIM,'HH24:MI:SS') + (SUBSTR(FIMTURNO,1,2)/24));
			END IF;
		ELSE
			IF (FNCTIMETOINT(DTFIM) < FNCTIME2TOINT(INITURNO)) THEN
				-- SE O TEMPO É ANTERIOR AO HORARIOTRABALHO ;;; TIMESTAMPADD(HOUR,SUBSTRING(INITURNO,1,2),DATE(DTINI));
				DATACALCFIM := TO_TIMESTAMP(DTINI,'HH24:MI:SS') + (SUBSTR(INITURNO,1,2)/24);
			ELSE
				DATACALCFIM := DTFIM;
			END IF;
		END IF;
		RETORNO := TIMEDIFF(DATACALCFIM,DATACALCINI);
    ELSE
        /*-->> MÉTODO PARA CÁLCULO DE HORAS*/
        -- SOMA HORAS FINAIS DO PRIMEIRO DIA
        HORAINIACUMULADA := (TO_CHAR(DTINI,'HH24') * 3600) + (TO_CHAR(DTINI,'MI') * 60) + TO_CHAR(DTINI,'SS');
        DATACALCFIM := TO_DATE((TO_CHAR(DTINI,'YYYY')||'-'||TO_CHAR(DTINI,'MM')||'-'||TO_CHAR(DTINI,'DD')||' '||FIMTURNO), 'YYYY-MM-DD HH24:MI:SS');
        HORAFIMACUMULADA := (TO_CHAR(DATACALCFIM,'HH24') * 3600) + (TO_CHAR(DATACALCFIM,'MI') * 60) + TO_CHAR(DATACALCFIM,'SS');
        SUMHORAS := HORAFIMACUMULADA - HORAINIACUMULADA;
        
        ICOUNT := 1;
        COUNTDIAS := ABS(DATEDIFF(DTFIM,DTINI));
    	WHILE (ICOUNT <= COUNTDIAS)
    	LOOP
        	DATAPROXIMA := (DTINI + ICOUNT);
            -- VERIRICAR SE A PROXIMA DATA EH IGUAL A DATA FIM
            IF (TO_DATE(DATAPROXIMA,'YYYY-MM-DD')=TO_DATE(DTFIM,'YYYY-MM-DD')) THEN
            	DATACALCINI := TO_DATE((TO_CHAR(DATAPROXIMA,'YYYY')||'-'||TO_CHAR(DATAPROXIMA,'MM')||'-'||TO_CHAR(DATAPROXIMA,'DD')||' '||INITURNO), 'YYYY-MM-DD HH24:MI:SS');
                HORAINIACUMULADA := (TO_CHAR(DATACALCINI,'HH24') * 3600) + (TO_CHAR(DATACALCINI,'MI') * 60) + TO_CHAR(DATACALCINI,'SS');
                HORAFIMACUMULADA := (TO_CHAR(DTFIM,'HH24') * 3600) + (TO_CHAR(DTFIM,'MI') * 60) + TO_CHAR(DTFIM,'SS');
                SUMHORAS := SUMHORAS + (HORAFIMACUMULADA - HORAINIACUMULADA);
            ELSE
                -- VERIFICAR FDS
                IF (TO_CHAR(DATAPROXIMA,'D')<>1 AND TO_CHAR(DATAPROXIMA,'D')<>7) THEN
            		-- VERIFICAR FERIADO
            		SELECT COUNT(*) INTO ISELECT FROM FKS_FERIADOS WHERE TO_CHAR(DT_FERIADO,'YYYY-MM_DD') = TO_CHAR(DATAPROXIMA,'YYYY-MM_DD');
                	IF (ISELECT <= 0) THEN
                        DATACALCINI := TO_DATE(TO_CHAR(DATAPROXIMA,'YYYY')||'-'||TO_CHAR(DATAPROXIMA,'MM')||'-'||TO_CHAR(DATAPROXIMA,'DD')||' '||INITURNO, 'YYYY-MM-DD HH24:MI:SS');
                        DATACALCFIM := TO_DATE(TO_CHAR(DATAPROXIMA,'YYYY')||'-'||TO_CHAR(DATAPROXIMA,'MM')||'-'||TO_CHAR(DATAPROXIMA,'DD')||' '||FIMTURNO, 'YYYY-MM-DD HH24:MI:SS');
                        HORAINIACUMULADA := (TO_CHAR(DATACALCINI,'HH24') * 3600) + (TO_CHAR(DATACALCINI,'MI') * 60) + TO_CHAR(DATACALCINI,'SS');
                        HORAFIMACUMULADA := (TO_CHAR(DATACALCFIM,'HH24') * 3600) + (TO_CHAR(DATACALCFIM,'MI') * 60) + TO_CHAR(DATACALCFIM,'SS');
                        SUMHORAS := SUMHORAS + (HORAFIMACUMULADA - HORAINIACUMULADA);
                    END IF;
                END IF;
            END IF;
            ICOUNT := ICOUNT + 1;
        END LOOP;

    	/*-->> MÉTODO PARA CÁLCULO DE HORAS*/
        HORACALC := FLOOR(SUMHORAS / 3600);
        SUMHORAS := SUMHORAS - (HORACALC * 3600);
        MINUTOCALC := FLOOR(SUMHORAS / 60);
        SUMHORAS := SUMHORAS - (MINUTOCALC * 60);
        SEGUNDOCALC := SUMHORAS;
        -- SET RETORNO = CAST(CONCAT(HORACALC,':',MINUTOCALC,':',SEGUNDOCALC) AS TIME);
        RETORNO := LPAD(HORACALC,2,'0')||':'||LPAD(MINUTOCALC,2,'0')||':'||LPAD(SEGUNDOCALC,2,'0');
	END IF;

  	RETURN RETORNO;
END;